services:
  luna-chat:
    image: ghcr.io/shun-shobon/luna-chat:latest
    env_file:
      - .env
    environment:
      TZ: ${TZ:-Asia/Tokyo}
    volumes:
      - ./data:/home/node
    stop_grace_period: 600s
    restart: unless-stopped
