services:
  luna-chat:
    build: .
    image: ghcr.io/shun-shobon/luna-chat:latest
    environment:
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN-}
      TZ: ${TZ-UTC}
    volumes:
      - luna-data:/home/node/.luna
    init: true
    restart: unless-stopped

volumes:
  luna-data:
