minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - "@openai/codex"
  - "@shun-shobon/oxfmt-config"
  - "@shun-shobon/oxlint-config"

allowBuilds:
  esbuild: true

saveExact: true

strictDepBuilds: true

trustPolicy: no-downgrade

trustPolicyIgnoreAfter: 10080
